config/routes.rb
Rails.application.routes.draw do
  



  get 'cells/index'
  get 'cells/edit'
  resources :goals
  resources :projects
  resources :questions
  resources :articles
  resources :users



  #Sessions routes  
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'sessions#home'

  
  #Questions routes
  post '/addquestiontag', to: 'questions#addtag', as: :addquestiontag
  post '/addanswer', to: 'questions#add_answer', as: :addanswer
  delete '/tagquestiondestroy', to: 'questions#destroy_tag', as: :destroyquestiontag
  delete '/destroyanswer/:id', to: 'questions#destroy_answer', as: :destroyanswer
  post '/likequestion/:id', to: 'questions#like', as: :likequestion
  post '/bestanswer', to: 'questions#best_answer', as: :bestanswer

  #Articles routes
  post '/addarticletag', to: 'articles#addtag', as: :addarticletag
  post '/addcomment', to: 'articles#add_comment', as: :addcomment
  delete '/destroycomment', to: 'articles#destroy_comment', as: :destroycomment
  delete '/tagarticledestroy', to: 'articles#destroy_tag', as: :destroyarticletag
  post '/likearticle/:id', to: 'articles#like', as: :likearticle

  #Project routes
  post '/addprojectmember', to: 'projects#add_member', as: :addprojectmember
  delete '/removemember', to: 'projects#remove_member', as: :removemember
  post '/addprojecttask', to: 'projects#add_task', as: :addprojecttask
  delete '/removetask', to: 'projects#remove_task', as: :removetask
  post '/projectdone', to: 'projects#done', as: :projectdone

  #Goals routes
  post '/addgoaltask', to: 'goals#add_task', as: :addgoaltask
  delete '/removetask/:id', to: 'goals#remove_task', as: :remove_task
  post '/checktask/:id', to: 'goals#check_task', as: :check_task

  #admin routes
  get 'admin/page', as: :admin
  post '/criadiretoria', to: 'admin#cria_diretoria', as: :criadiretoria
  post '/addmembrodiretoria', to: 'admin#add_membro_diretoria', as: :addmembrodiretoria
  post '/criacelula', to: 'admin#cria_celula', as: :criacelula
  post '/addmembrocelula', to:'admin#add_membro_celula', as: :addmembrocelula
  
  #Directions routes
  get 'directions/index', as: :directions
  get 'directions/edit/:id',to: 'directions#edit', as: :edit_directions
  post '/editadiretoria', to: 'directions#edita_diretoria', as: :editadiretoria
  post '/add_membro_diretoria', to: 'directions#add_membro_diretoria', as: :add_membro_diretoria

  #Cells routes 
  get 'cells/index', as: :cells
  get 'cells/edit/:id',to: 'cells#edit', as: :edit_cells
  post '/editacelula', to: 'cells#edita_celula', as: :editacelula
  post '/add_membro_celula', to: 'cells#add_membro_celula', as: :add_membro_celula
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :like_question, dependent: :destroy
  has_many :answer, dependent: :destroy
  has_many :tag_question, dependent: :destroy
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include QuestionsHelper
  
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :expulsa_nao_logados

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    #tags de cada questão
    @tags ||= []
    TagQuestion.all.each do |tag_question|
      @tag = Tag.all.find(tag_question.tag_id)
      if tag_question.question_id == @question.id
        @tags.push(@tag)
      end
    end

      #selecionar tags
    @tag_question = TagQuestion.new
    @tag_all = Tag.all

    #visualizar comentarios
    @answers = []
    Answer.all.each do |answer|
      if answer.question_id == @question.id
        @answers.push(answer)
      end
    end

    #criar comentarios/respostas
    @answer = Answer.new
    
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  
  def like
    @question_id = params[:id]
    @likequestion = user_already_like(current_user.id, @question_id)
    if @likequestion.nil?
      LikeQuestion.create(user_id: current_user.id, question_id: @question_id)
    else
      @likequestion.destroy
    end
    redirect_to question_path(@question_id)
  end

  def addtag
    @question_id = params[:tag_question][:question_id]
    @tag_id = params[:tag_question][:tag_id]
    @tagquestions = TagQuestion.where(question: @question_id)
    @tagquestions = @tagquestions.find_by_tag_id(@tag_id)
    if @tagquestions == nil
      TagQuestion.create({question_id:  @question_id, tag_id: @tag_id})
    end
    redirect_to question_path(@question_id)
  end

  def add_answer
    @question_id = params[:answer][:question_id]
    @content = params[:answer][:content]
    Answer.create({content: @content, user_id: current_user.id, question_id: @question_id, best: false})
    redirect_to question_path(@question_id)
  end

  def destroy_tag
    @question_id = params[:question]
    @tag_id = params[:tag]
    @tagquestions = TagQuestion.where(question: @question_id)
    @tagquestions = @tagquestions.find_by_tag_id(@tag_id)
    @tagquestions.destroy
  end

  def destroy_answer
    @answer = Answer.find(params[:id])
    @answer.destroy
    #adiocionar caminho
  end

  def best_answer
    @answer = Answer.find(params[:answer])
    @question_id = params[:question]
    @best_answer = has_best(@question_id)
    if @best_answer.nil?
      @answer.best = true
    else 
      if !@answer.best
        @answer.best = true
        @best_answer.best = false
        @best_answer.save
      else
        @answer.best = false
      end
    end
    @answer.save
    redirect_to question_path(@question_id)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :content)
    end

    def tags_per_question
      @tags = []
      TagQuestion.all.each do |tag_question|
        if tag_question.question_id == @question.id
          @tags << Tag.all.find(tag_question.tag_id)
        end
      end
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper

    def answer_user(user)
        @answer_user = User.find(user)
    end

    def question_likes(question)
        @question_likes = LikeQuestion.where(question_id: question.id)
    end

    def user_already_like(user_id, question_id)
        @alreadylike = LikeQuestion.where(user_id: user_id)
        @alreadylike = @alreadylike.find_by_question_id(question_id)
    end

    def has_best(question_id)
        @answers = Answer.where(question_id: question_id)
        @answers = @answers.find_by_best(true)
    end
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<section class = "question-edit">
<h1>Editar Pergunta</h1>

<%= render 'form', question: @question %>

<div id = "ref">
    <%= link_to 'Show', @question %> |
    <%= link_to 'Back', questions_path %>
</div>
</section>

app/views/questions/index.html.erb
<section class = "question-index">
<h1>Perguntas</h1>

<table class = "container">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.content %></td>
        <td><%= question.user.name.capitalize %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

</section>

app/views/questions/new.html.erb
<section class = "question-new">
<h1>Faça uma pergunta</h1>

<%= render 'form', question: @question %>
<div id = "ref">
    <%= link_to 'Back', questions_path %>
</div>

</section>

app/views/questions/show.html.erb
<section class = "question-show">

  <p>
    <strong>Title:</strong>
    <%= @question.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @question.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @question.user.name.capitalize %>
  </p>

  <p> <%= question_likes(@question).size %>
    <%= link_to 'Like', likequestion_path(@question.id), method: :post %> </li>
  </p>

  <p>
  <strong>Tags:</strong>
  <%= @tags.size%>
  <ul>
  <% @tags.each do |tag|%>
      <li> <%= tag.name %> </li>
  <%end%>
  </ul>
</p>



  <p>Adicionar tags:
    <%= form_for(@tag_question, url: :addquestiontag) do |form| %>
      <%= form.select(:tag_id, @tag_all.collect { |tag| [tag.name, tag.id] }) %>
      <%= form.hidden_field :question_id,value: @question.id %>
      <%= form.submit %>
  <%end%>

  

  <p> 
  <strong>Respostas:</strong>
    <% @answers.each do |answer|%>
      <%= answer_user(answer.user_id).name.capitalize %>: <%= answer.content%>
      <%if answer.best %>
      <strong>Melhor resposta</strong>
      <%end%>
      <%if answer.user_id == current_user.id%>
      <%= link_to 'Apagar', destroyanswer_path(answer), method: :delete %>
      <%end%>
      <%if @question.user_id == current_user.id%>
      <%= link_to 'Melhor resposta', '/bestanswer?answer='+answer.id.to_s+'&question='+@question.id.to_s, method: :post %>
      <%end%>
      <br>
    <%end%>
  </p>

  <p> Adicionar respostas/comentários:
    <%= form_for(@answer, url: :addanswer) do |form| %>
      <%= form.text_area :content %>
      <%= form.hidden_field :question_id,value: @question.id %>
      <%= form.submit %>
  <%end%>
  <div id = "ref">   
    <%= link_to 'Edit', edit_question_path(@question) %> |
    <%= link_to 'Back', questions_path %>
  </div>
</section>