config/routes.rb
Rails.application.routes.draw do
  



  get 'cells/index'
  get 'cells/edit'
  resources :goals
  resources :projects
  resources :questions
  resources :articles
  resources :users



  #Sessions routes  
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'sessions#home'

  
  #Questions routes
  post '/addquestiontag', to: 'questions#addtag', as: :addquestiontag
  post '/addanswer', to: 'questions#add_answer', as: :addanswer
  delete '/tagquestiondestroy', to: 'questions#destroy_tag', as: :destroyquestiontag
  delete '/destroyanswer/:id', to: 'questions#destroy_answer', as: :destroyanswer
  post '/likequestion/:id', to: 'questions#like', as: :likequestion
  post '/bestanswer', to: 'questions#best_answer', as: :bestanswer

  #Articles routes
  post '/addarticletag', to: 'articles#addtag', as: :addarticletag
  post '/addcomment', to: 'articles#add_comment', as: :addcomment
  delete '/destroycomment', to: 'articles#destroy_comment', as: :destroycomment
  delete '/tagarticledestroy', to: 'articles#destroy_tag', as: :destroyarticletag
  post '/likearticle/:id', to: 'articles#like', as: :likearticle

  #Project routes
  post '/addprojectmember', to: 'projects#add_member', as: :addprojectmember
  delete '/removemember', to: 'projects#remove_member', as: :removemember
  post '/addprojecttask', to: 'projects#add_task', as: :addprojecttask
  delete '/removetask', to: 'projects#remove_task', as: :removetask
  post '/projectdone', to: 'projects#done', as: :projectdone

  #Goals routes
  post '/addgoaltask', to: 'goals#add_task', as: :addgoaltask
  delete '/removetask/:id', to: 'goals#remove_task', as: :remove_task
  post '/checktask/:id', to: 'goals#check_task', as: :check_task

  #admin routes
  get 'admin/page', as: :admin
  post '/criadiretoria', to: 'admin#cria_diretoria', as: :criadiretoria
  post '/addmembrodiretoria', to: 'admin#add_membro_diretoria', as: :addmembrodiretoria
  post '/criacelula', to: 'admin#cria_celula', as: :criacelula
  post '/addmembrocelula', to:'admin#add_membro_celula', as: :addmembrocelula
  
  #Directions routes
  get 'directions/index', as: :directions
  get 'directions/edit/:id',to: 'directions#edit', as: :edit_directions
  post '/editadiretoria', to: 'directions#edita_diretoria', as: :editadiretoria
  post '/add_membro_diretoria', to: 'directions#add_membro_diretoria', as: :add_membro_diretoria

  #Cells routes 
  get 'cells/index', as: :cells
  get 'cells/edit/:id',to: 'cells#edit', as: :edit_cells
  post '/editacelula', to: 'cells#edita_celula', as: :editacelula
  post '/add_membro_celula', to: 'cells#add_membro_celula', as: :add_membro_celula
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :like_article, dependent: :destroy
  has_many :comment, dependent: :destroy
  has_many :tag_article, dependent: :destroy
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :expulsa_nao_logados

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    #mostrar tags do artigo
    @tags ||= []
    TagArticle.all.each do |tag_article|
      @tag = Tag.all.find(tag_article.tag_id)
      if tag_article.article_id == @article.id
        @tags.push(@tag)
      end
    end

    #add tags
    @tag_article = TagArticle.new
    @tag_all = Tag.all

    #adicionar comentarios
    @comment = Comment.new

    #ver comentarios
    @comments ||= []
    Comment.all.each do |comment|
      if comment.article_id == @article.id
        @comments.push(comment)
      end
    end
      
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

    
  def addtag
    @article_id = params[:tag_article][:article_id]
    @tag_id = params[:tag_article][:tag_id]
    @tagarticles = TagArticle.where(article: @article_id)
    @tagarticles = @tagarticles.find_by_tag_id(@tag_id)
    if @tagarticles == nil
      TagArticle.create({article_id: @article_id, tag_id: @tag_id})
    end
    redirect_to article_path(params[:tag_article][:article_id])
  end

  def add_comment
    Comment.create({content: params[:comment][:content], article_id: params[:comment][:article_id], user_id: current_user.id })
    redirect_to article_path(params[:comment][:article_id])
  end

  def destroy_tag
    @article_id = params[:article]
    @tag_id = params[:tag]
    @tagarticles = TagArticle.where(article: @article_id)
    @tagarticles = @tagarticles.find_by_tag_id(@tag_id)
    @tagarticles.destroy
    redirect_to article_path(@article_id)
  end

  def destroy_comment
    @comment = Comment.find(params[:comment])
    @comment.destroy
    @article_id = params[:article]
    redirect_to article_path(@article_id)
  end

  def like
    @article_id = params[:id]
    @likearticle = user_already_like(current_user.id, @article_id)
    if @likearticle.nil?
      LikeArticle.create(user_id: current_user.id, article_id: @article_id)
    else
      @likearticle.destroy
    end
    redirect_to article_path(@article_id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def comment_user(user) #pega usuario dono do comment
        @comment_user = User.find(user)
    end

    def article_likes(article) #retorna aray de likes do artigo
        @article_likes = LikeArticle.where(article_id: article.id)
    end

    def user_already_like(user_id, article_id) #confere se user ja curtiu
        @alreadylike = LikeArticle.where(user_id: user_id)
        @alreadylike = @alreadylike.find_by_article_id(article_id)
    end
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Titulo %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :Conteudo %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit "Criar artigo" %>
    Enviando como: <%= current_user.name.capitalize%>
  </div>
<% end %>

app/views/articles/edit.html.erb
<section id = "artigo-edit">
<h1>Editar Artigo</h1>

<%= render 'form', article: @article %>

<div id = "ref">
<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>
</div>

</section>

app/views/articles/index.html.erb
<section class = "artigos-index">
<h1>Artigos</h1>
<div class = "container todo-artigo">
    <% @articles.each do |article| %>
        <div class = "cada-artigo">
        <p><%= article.title %></p>
        <p><%= article.content %></p>
        <p><%= article.user.name.capitalize %></p>
        <p><%= link_to 'Show', article %></p>
        <p><%= link_to 'Edit', edit_article_path(article) %></p>
        <p><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        </div>
    <% end %>
</div>

<br>

<%= link_to 'New Article', new_article_path %>
</section>

app/views/articles/new.html.erb
<section class = "artigo-new">

<h1> Novo Artigo </h1>

<%= render 'form', article: @article %>

<div id = "ref">
    <%= link_to 'Back', articles_path %>
</div>

</section>

app/views/articles/show.html.erb
<section class = "articles-show">

  <p>
    <strong>Titulo</strong>
  <%= @article.title %>
  </p>

  <p>
    <strong>Conteúdo</strong>
  <%= @article.content %>
  </p>

  <p>
    <strong>Quem postou?</strong>
  <%= @article.user.name.capitalize %>
  </p>

<p> <%= article_likes(@article).size %>
  <%= link_to 'Like', likearticle_path(@article.id), method: :post %> 
  <%=image_tag("like.png", alt:"Foto da Logo", class:"like")%>
</p>

  <p>
  <strong>Tags:</strong>
  <%= @tags.size%>
  <ul>
  <% @tags.each do |tag|%>
      <li> <%= tag.name %> </li>
  <%end%>
  </ul>
</p>

<p>
  <%= form_for(@tag_article, url: :addarticletag) do |form| %>
    <%= form.select(:tag_id, @tag_all.collect { |tag| [tag.name, tag.id] }) %>
    <%= form.hidden_field :article_id,value: @article.id %>
    <%= form.submit %>
<%end%>

<p> 
<strong>Feedbacks:</strong><br>
  <% @comments.each do |comment|%>
    <%= comment_user(comment.user_id).name.capitalize %>: <%= comment.content%>
    <%if comment.user_id == current_user.id %>
    <%= link_to 'Apagar', '/destroycomment?article='+@article.id.to_s+'&comment='+comment.id.to_s, method: :delete %> <br>
    <%end%>
  <%end%>
</p>

<p> Adicionar Feedbacks: 
  <%= form_for(@comment, url: :addcomment) do |form| %>
    <%= form.text_area :content %>
    <%= form.hidden_field :article_id,value: @article.id %>
    <%= form.submit %>
  <%end%>
</p>

<div id = "ref">
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>
</div>

</section>