config/routes.rb
Rails.application.routes.draw do
  



  get 'cells/index'
  get 'cells/edit'
  resources :goals
  resources :projects
  resources :questions
  resources :articles
  resources :users



  #Sessions routes  
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'sessions#home'

  
  #Questions routes
  post '/addquestiontag', to: 'questions#addtag', as: :addquestiontag
  post '/addanswer', to: 'questions#add_answer', as: :addanswer
  delete '/tagquestiondestroy', to: 'questions#destroy_tag', as: :destroyquestiontag
  delete '/destroyanswer/:id', to: 'questions#destroy_answer', as: :destroyanswer
  post '/likequestion/:id', to: 'questions#like', as: :likequestion
  post '/bestanswer', to: 'questions#best_answer', as: :bestanswer

  #Articles routes
  post '/addarticletag', to: 'articles#addtag', as: :addarticletag
  post '/addcomment', to: 'articles#add_comment', as: :addcomment
  delete '/destroycomment', to: 'articles#destroy_comment', as: :destroycomment
  delete '/tagarticledestroy', to: 'articles#destroy_tag', as: :destroyarticletag
  post '/likearticle/:id', to: 'articles#like', as: :likearticle

  #Project routes
  post '/addprojectmember', to: 'projects#add_member', as: :addprojectmember
  delete '/removemember', to: 'projects#remove_member', as: :removemember
  post '/addprojecttask', to: 'projects#add_task', as: :addprojecttask
  delete '/removetask', to: 'projects#remove_task', as: :removetask
  post '/projectdone', to: 'projects#done', as: :projectdone

  #Goals routes
  post '/addgoaltask', to: 'goals#add_task', as: :addgoaltask
  delete '/removetask/:id', to: 'goals#remove_task', as: :remove_task
  post '/checktask/:id', to: 'goals#check_task', as: :check_task

  #admin routes
  get 'admin/page', as: :admin
  post '/criadiretoria', to: 'admin#cria_diretoria', as: :criadiretoria
  post '/addmembrodiretoria', to: 'admin#add_membro_diretoria', as: :addmembrodiretoria
  post '/criacelula', to: 'admin#cria_celula', as: :criacelula
  post '/addmembrocelula', to:'admin#add_membro_celula', as: :addmembrocelula
  
  #Directions routes
  get 'directions/index', as: :directions
  get 'directions/edit/:id',to: 'directions#edit', as: :edit_directions
  post '/editadiretoria', to: 'directions#edita_diretoria', as: :editadiretoria
  post '/add_membro_diretoria', to: 'directions#add_membro_diretoria', as: :add_membro_diretoria

  #Cells routes 
  get 'cells/index', as: :cells
  get 'cells/edit/:id',to: 'cells#edit', as: :edit_cells
  post '/editacelula', to: 'cells#edita_celula', as: :editacelula
  post '/add_membro_celula', to: 'cells#add_membro_celula', as: :add_membro_celula
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/goal.rb
class Goal < ApplicationRecord
    has_many :goal_task, dependent: :destroy
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  include GoalsHelper
  before_action :set_goal, only: [:show, :edit, :update, :destroy]
  before_action :expulsa_nao_logados

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
    #adicionar tarefa
    @goal_task = GoalTask.new
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_task
    @goal_id = params[:goal_task][:goal_id]
    @name = params[:goal_task][:name]
    GoalTask.create(goal_id: @goal_id, name: @name, check: false)
    redirect_to edit_goal_path(@goal_id)
  end

  def remove_task
    @task = GoalTask.find(params[:id])
    @goal_id = @task.goal_id
    @task.destroy
    redirect_to edit_goal_path(@goal_id)
  end

  def check_task
    @task = GoalTask.find(params[:id])
    @goal_id = @task.goal_id
    if @task.check
      @task.check = false
    else
      @task.check = true
    end
    @task.save
    redirect_to edit_goal_path(@goal_id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:name)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
    
    def tasks(goal_id)
        @tasks = GoalTask.where(goal_id: goal_id)
    end

end

app/views/goals/_form.html.erb
<%= form_with(model: goal, local: true) do |form| %>
  <% if goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Meta %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<section class = "metas-edit">
<h1>Editar Metas</h1>

<%= render 'form', goal: @goal %>

<p>
  <strong>Tarefas:</strong>
  <ul>
  <% tasks(@goal.id).each do |task| %>
  <li><%= task.name %>
    <%= link_to 'Check', check_task_path(task.id), method: :post  %></li>
    <%= link_to 'Remover', remove_task_path(task.id), method: :delete  %></li>
  <%end%>
  </ul>
</p>

<p>
  <strong>Adicionar tarefas:</strong>
  <%= form_for(@goal_task, url: :addgoaltask) do |form| %>
  <%= form.text_field :name %>
  <%= form.hidden_field :goal_id, value: @goal.id %>
  <%= form.submit "Adicionar tarefa"%>
  <%end%>
</p>

<div id = "ref">
  <%= link_to 'Show', @goal %> |
  <%= link_to 'Back', goals_path %>
</div>
</section>

app/views/goals/index.html.erb
<section class = "metas-index">
<p id="notice"><%= notice %></p>

<h1>METAS</h1>

<table class = "container">
  <thead>
    <tr>
      <th>Name</th>
      <th>tarefa</th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <tr>
        <td><%= goal.name %></td>
        <td><ul>
        <% tasks(goal.id).each do |task| %>
        <li><%= task.name %>
        <%if task.check%> (icone de check)
        <%end%>
        </li>
        <%end%>
        </ul>
        
        <td><%= link_to 'Show', goal %></td>
        <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
        <td><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goal', new_goal_path %>
</section>

app/views/goals/new.html.erb
<section class = "metas-new">
    
    <h1> Nova Meta </h1>

    <%= render 'form', goal: @goal %>

    <div id = "ref">
    <%= link_to 'Back', goals_path %>
    </div>
</section>

app/views/goals/show.html.erb
<section class = "metas-show">

  <p>
    <strong>Name:</strong>
    <%= @goal.name %>
  </p>

  <p>
    <strong>Tarefas:</strong>
    <ul>
    <% tasks(@goal.id).each do |task| %>
    <li><%= task.name %>
    <%if task.check%> (icone de check)
    <%end%>
    </li>
    <%end%>
    </ul>
  </p>

<div id = "ref">
  <%= link_to 'Edit', edit_goal_path(@goal) %> |
  <%= link_to 'Back', goals_path %>
  </div>

</section>