config/routes.rb
Rails.application.routes.draw do
  



  get 'cells/index'
  get 'cells/edit'
  resources :goals
  resources :projects
  resources :questions
  resources :articles
  resources :users



  #Sessions routes  
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root 'sessions#home'

  
  #Questions routes
  post '/addquestiontag', to: 'questions#addtag', as: :addquestiontag
  post '/addanswer', to: 'questions#add_answer', as: :addanswer
  delete '/tagquestiondestroy', to: 'questions#destroy_tag', as: :destroyquestiontag
  delete '/destroyanswer/:id', to: 'questions#destroy_answer', as: :destroyanswer
  post '/likequestion/:id', to: 'questions#like', as: :likequestion
  post '/bestanswer', to: 'questions#best_answer', as: :bestanswer

  #Articles routes
  post '/addarticletag', to: 'articles#addtag', as: :addarticletag
  post '/addcomment', to: 'articles#add_comment', as: :addcomment
  delete '/destroycomment', to: 'articles#destroy_comment', as: :destroycomment
  delete '/tagarticledestroy', to: 'articles#destroy_tag', as: :destroyarticletag
  post '/likearticle/:id', to: 'articles#like', as: :likearticle

  #Project routes
  post '/addprojectmember', to: 'projects#add_member', as: :addprojectmember
  delete '/removemember', to: 'projects#remove_member', as: :removemember
  post '/addprojecttask', to: 'projects#add_task', as: :addprojecttask
  delete '/removetask', to: 'projects#remove_task', as: :removetask
  post '/projectdone', to: 'projects#done', as: :projectdone

  #Goals routes
  post '/addgoaltask', to: 'goals#add_task', as: :addgoaltask
  delete '/removetask/:id', to: 'goals#remove_task', as: :remove_task
  post '/checktask/:id', to: 'goals#check_task', as: :check_task

  #admin routes
  get 'admin/page', as: :admin
  post '/criadiretoria', to: 'admin#cria_diretoria', as: :criadiretoria
  post '/addmembrodiretoria', to: 'admin#add_membro_diretoria', as: :addmembrodiretoria
  post '/criacelula', to: 'admin#cria_celula', as: :criacelula
  post '/addmembrocelula', to:'admin#add_membro_celula', as: :addmembrocelula
  
  #Directions routes
  get 'directions/index', as: :directions
  get 'directions/edit/:id',to: 'directions#edit', as: :edit_directions
  post '/editadiretoria', to: 'directions#edita_diretoria', as: :editadiretoria
  post '/add_membro_diretoria', to: 'directions#add_membro_diretoria', as: :add_membro_diretoria

  #Cells routes 
  get 'cells/index', as: :cells
  get 'cells/edit/:id',to: 'cells#edit', as: :edit_cells
  post '/editacelula', to: 'cells#edita_celula', as: :editacelula
  post '/add_membro_celula', to: 'cells#add_membro_celula', as: :add_membro_celula
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :like_article, dependent: :destroy
  has_many :comment, dependent: :destroy
  has_many :tag_article, dependent: :destroy
end

app/models/cell.rb
class Cell < ApplicationRecord
end

app/models/cell_user.rb
class CellUser < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/direction.rb
class Direction < ApplicationRecord
end

app/models/goal.rb
class Goal < ApplicationRecord
    has_many :goal_task, dependent: :destroy
end

app/models/goal_task.rb
class GoalTask < ApplicationRecord
  belongs_to :goal
end

app/models/like_article.rb
class LikeArticle < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :project_task, dependent: :destroy
    has_many :project_user, dependent: :destroy
end

app/models/project_task.rb
class ProjectTask < ApplicationRecord
end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :like_question, dependent: :destroy
  has_many :answer, dependent: :destroy
  has_many :tag_question, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/tag_article.rb
class TagArticle < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/models/tag_question.rb
class TagQuestion < ApplicationRecord
  belongs_to :tag
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
    
    mount_uploader :picture, PictureUploader

    has_many :articles

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
      end

end

app/helpers/admin_helper.rb
module AdminHelper

    def membros_diretoria(direction_id)
        @membros_linhas = DirectionUser.where(direction_id: direction_id)
        @membros = []
        @membros_linhas.each do |linha|
            @membros.push(User.find(linha.user_id))
        end
        @membros
    end

    def director?(direction_id, user_id)
        @membros_diretoria = DirectionUser.where(direction_id: direction_id)
        @director = @membros_diretoria.find_by_director(true)
        if @director != nil
            @director.user_id == user_id
        end
    end

    def membros_celula(cell_id)
        @membros_linhas = CellUser.where(cell_id: cell_id)
        @membros = []
        @membros_linhas.each do |linha|
            @membros.push(User.find(linha.user_id))
        end
        @membros
    end

    def manager?(cell_id, user_id)
        @membros_celula = CellUser.where(cell_id: cell_id)
        @manager = @membros_celula.find_by_manager(true)
        if @manager != nil
            @manager.user_id == user_id
        end
    end

end

app/helpers/cells_helper.rb
module CellsHelper
    
    def gerente(cell_id)
        @cell_lines = CellUser.where(cell_id: cell_id)
        @manager_line = @cell_lines.find_by_manager(true)
        if @manager_line != nil
            @manager = User.find(@manager_line.user_id)
        end
    end

    def membros(cell_id)
        @cell_lines = CellUser.where(cell_id: cell_id)
        @member = []
        @cell_lines.each do |line|
            @member.push(User.find(line.user_id))
        end
        @member
    end
    
end

app/helpers/goals_helper.rb
module GoalsHelper
    
    def tasks(goal_id)
        @tasks = GoalTask.where(goal_id: goal_id)
    end

end

app/views/admin/page.html.erb
<section class = "admin container">
    <h1>Pagina de admin</h1>

    <h3><strong>Diretorias:</strong></h3>
    <p><ul>
    <% Direction.all.each do |direction| %>
    <li> <%=direction.name%> </li>
    <%end%>
    </ul> </p>

    <h3><strong>Criar diretoria:</strong></h3>
    <p>
    <%= form_for(@direction, url: :criadiretoria) do |form| %>
        Nome da diretoria: <%= form.text_field :name %>
        <%= form.submit "Criar diretoria"%>
        <%end%>
    </p>

    <h3><strong>Membros da diretoria:</strong></h3>
    <p>
    <% Direction.all.each do |direction| %>
        <ul> <strong><%=direction.name%> </strong>
        <%membros_diretoria(direction.id).each do |membro|%>
            <li> <%= membro.name%> 
            <%if director?(direction.id, membro.id)%>
            <strong>diretor</strong> </li>
            <%end%>
        <%end%>
        </ul>

    <%end%>
    </ul> </p>


    <h3><strong>Adicionar membros a diretoria:</strong></h3>
    <p>
    <%= form_for(@direction_user, url: :addmembrodiretoria) do |form| %>
        <%= form.select(:user_id, User.all.collect { |user| [user.name, user.id] }) %>
        <%= form.select(:direction_id, Direction.all.collect { |direction| [direction.name, direction.id] }) %>
        <%= form.check_box :director %> Diretor
        <%= form.submit "Adicionar membro"%>
        <%end%>
    </p>

    <h3><strong>Celulas:</strong></h3>
    <p><ul>
    <% Cell.all.each do |cell| %>
    <li> <%=cell.name%> </li>
    <%end%>
    </ul> </p>

    <h3><strong>Criar Celula:</strong></h3>
    <p>
    <%= form_for(@cell, url: :criacelula) do |form| %>
        Nome da celula: <%= form.text_field :name %>
        <%= form.submit "Criar celula"%>
        <%end%>
    </p>

    <h3><strong>Membros da celula:</strong></h3>
    <p>
    <% Cell.all.each do |cell| %>
        <ul> <strong><%=cell.name%> </strong>
        <%membros_celula(cell.id).each do |membro|%>
            <li> <%= membro.name%> </li>
        <%end%>
        </ul>

    <%end%>
    </ul> </p>


    <h3><strong>Adicionar membros a celula:</strong></h3>
    <p>
    <%= form_for(@cell_user, url: :addmembrocelula) do |form| %>
        <%= form.select(:user_id, User.all.collect { |user| [user.name, user.id] }) %>
        <%= form.select(:cell_id, Cell.all.collect { |cell| [cell.name, cell.id] }) %>
        <%= form.check_box :manager %> Gerente
        <%= form.submit "Adicionar membro"%>
        <%end%>
    </p>

</section>

app/views/layouts/_header.html.erb
<nav id = "navbar">
<%=image_tag("logo-branca.png", alt:"Foto da Logo")%>
 <ul>
     <li><%= link_to 'Perfil', current_user %></li>
     <li><%= link_to 'Artigos',articles_path %></li>
     <li><%= link_to 'Metas', goals_path %></li>
     <li><%= link_to 'Perguntas', questions_path %></li>
     <li><%= link_to 'Projetos', projects_path %></li>
     <li><%= link_to 'Diretorias', directions_path %></li>
     <li><%= link_to 'Celulas', cells_path %>
     <li><%= link_to 'Sair', logout_path, method: :delete %></li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wikia1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header><%= render partial: "layouts/header"%></header>
  <% if logged_in?%>

  <% end %>
    <%= yield %>
  </body>
</html>